from __future__ import annotations

import io
import os
import re
import tempfile
import warnings
from pathlib import Path
from uuid import uuid4

from PIL import Image, ImageOps, UnidentifiedImageError
from psycopg import sql

from app.print_queue import PrintQueueService
from app.printer import QueuedZplDocument
from app.schemas import LabelImage, PrintResponse
from app.settings import Settings


MAX_UPLOAD_BYTES = 5 * 1024 * 1024
MAX_IMAGE_SIDE = 4096
SLOT_SIZE = (202, 172)
COLUMN_X = (32, 302, 575)
ORIGIN_Y = 14

SCHEMA_SQL = """
create table if not exists label_images (
    id bigint generated by default as identity primary key,
    name text not null,
    filename text not null unique,
    width integer not null check (width > 0),
    height integer not null check (height > 0),
    created_at timestamptz not null default now()
);
"""


class CustomLabelError(Exception):
    def __init__(self, message: str, status_code: int = 400) -> None:
        super().__init__(message)
        self.status_code = status_code


def normalize_image(data: bytes, filename: str) -> Image.Image:
    if len(data) > MAX_UPLOAD_BYTES:
        raise CustomLabelError("La imagen supera el limite de 5 MB.", 413)
    if Path(filename).suffix.lower() not in {".png", ".jpg", ".jpeg"}:
        raise CustomLabelError("Solo se permiten imagenes PNG y JPG.", 415)
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            with Image.open(io.BytesIO(data)) as image:
                if image.format not in {"PNG", "JPEG"}:
                    raise CustomLabelError("El contenido del archivo no es PNG ni JPG.", 415)
                if max(image.size) > MAX_IMAGE_SIDE:
                    raise CustomLabelError("La imagen no debe superar 4096 x 4096 pixeles.")
                if getattr(image, "n_frames", 1) != 1:
                    raise CustomLabelError("No se admiten imagenes animadas.")
                image.verify()
            with Image.open(io.BytesIO(data)) as image:
                oriented = ImageOps.exif_transpose(image).convert("RGBA")
                background = Image.new("RGB", oriented.size, "white")
                background.paste(oriented, mask=oriented.getchannel("A"))
                # A new image strips EXIF and other metadata from the upload.
                normalized = Image.new("RGB", background.size)
                normalized.paste(background)
                return normalized
    except CustomLabelError:
        raise
    except (UnidentifiedImageError, OSError, ValueError, SyntaxError,
            Image.DecompressionBombWarning, Image.DecompressionBombError) as exc:
        raise CustomLabelError("El archivo esta corrupto o no es una imagen valida.") from exc


def label_bitmap(image: Image.Image) -> Image.Image:
    fitted = ImageOps.contain(image.convert("L"), SLOT_SIZE, Image.Resampling.LANCZOS)
    canvas = Image.new("L", SLOT_SIZE, 255)
    canvas.paste(fitted, ((SLOT_SIZE[0] - fitted.width) // 2, (SLOT_SIZE[1] - fitted.height) // 2))
    return canvas.point(lambda pixel: 255 if pixel >= 128 else 0, mode="1")


def png_bytes(image: Image.Image) -> bytes:
    output = io.BytesIO()
    image.save(output, format="PNG")
    return output.getvalue()


def build_custom_label_documents(bitmap: Image.Image, quantity: int) -> list[QueuedZplDocument]:
    if not 1 <= quantity <= 400:
        raise CustomLabelError("La cantidad debe estar entre 1 y 400 etiquetas.")
    # ZPL uses 1 for black. Pillow's mode 1 uses 1 for white; invert before packing.
    payload = ImageOps.invert(bitmap.convert("L")).convert("1", dither=Image.Dither.NONE).tobytes()
    row_bytes = (bitmap.width + 7) // 8
    graphic = f"^GFA,{len(payload)},{len(payload)},{row_bytes},{payload.hex().upper()}^FS"
    documents: list[QueuedZplDocument] = []
    for start in range(0, quantity, 3):
        count = min(3, quantity - start)
        fields = "".join(f"^FO{x},{ORIGIN_Y}{graphic}" for x in COLUMN_X[:count])
        zpl = f"^XA^PON^PMN^LH0,0^LT0^LS0^LRN^MMT^PW799^LL200{fields}^PQ1^XZ"
        documents.append(QueuedZplDocument(zpl=zpl, item_counts={0: count}))
    return documents


class CustomLabelService:
    def __init__(self, settings: Settings, queue: PrintQueueService) -> None:
        self.settings = settings
        self.queue = queue
        self.directory = Path(settings.label_images_dir)

    def ensure_schema(self) -> None:
        if not self.settings.use_postgres:
            return
        self.directory.mkdir(parents=True, exist_ok=True)
        with self.queue._connect() as conn:
            conn.execute(SCHEMA_SQL)
            table = sql.Identifier(self.settings.history_table)
            conn.execute(sql.SQL("alter table {} add column if not exists kind text not null default 'individual'").format(table))
            conn.execute(sql.SQL("alter table {} add column if not exists image_id bigint").format(table))
            conn.execute(sql.SQL("alter table {} add column if not exists image_name text").format(table))

    def _require_database(self) -> None:
        if not self.settings.use_postgres:
            raise CustomLabelError("Las etiquetas personalizadas requieren PostgreSQL.", 503)

    def list_images(self) -> list[LabelImage]:
        self._require_database()
        with self.queue._connect() as conn:
            rows = conn.execute("select id, name, width, height, created_at from label_images order by created_at desc, id desc").fetchall()
        return [LabelImage.model_validate(row) for row in rows]

    def upload(self, data: bytes, filename: str, name: str) -> LabelImage:
        self._require_database()
        name = name.strip()
        if not 1 <= len(name) <= 120:
            raise CustomLabelError("El nombre debe contener entre 1 y 120 caracteres.")
        image = normalize_image(data, filename)
        stored_filename = f"{uuid4().hex}.png"
        self.directory.mkdir(parents=True, exist_ok=True)
        target = self.directory / stored_filename
        temporary: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(dir=self.directory, suffix=".tmp", delete=False) as file:
                temporary = Path(file.name)
                image.save(file, format="PNG")
            os.replace(temporary, target)
            with self.queue._connect() as conn:
                row = conn.execute(
                    """insert into label_images (name, filename, width, height)
                       values (%s, %s, %s, %s)
                       returning id, name, width, height, created_at""",
                    (name, stored_filename, image.width, image.height),
                ).fetchone()
            return LabelImage.model_validate(row)
        except Exception:
            target.unlink(missing_ok=True)
            raise
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)

    def get_image(self, image_id: int) -> tuple[LabelImage, Path]:
        self._require_database()
        with self.queue._connect() as conn:
            row = conn.execute("select * from label_images where id = %s", (image_id,)).fetchone()
        if row is None:
            raise CustomLabelError("Imagen no encontrada.", 404)
        if not re.fullmatch(r"[0-9a-f]{32}\.png", row["filename"]):
            raise CustomLabelError("El archivo de la imagen no es valido.", 404)
        path = self.directory / row["filename"]
        if not path.is_file():
            raise CustomLabelError("El archivo de la imagen no esta disponible.", 404)
        return LabelImage.model_validate(row), path

    def bitmap(self, image_id: int) -> tuple[LabelImage, Image.Image]:
        image, path = self.get_image(image_id)
        try:
            with Image.open(path) as source:
                return image, label_bitmap(source)
        except (OSError, ValueError) as exc:
            raise CustomLabelError("No se pudo leer la imagen almacenada.") from exc

    def print_image(self, image_id: int, quantity: int, user: str) -> PrintResponse:
        image, bitmap = self.bitmap(image_id)
        documents = build_custom_label_documents(bitmap, quantity)
        with self.queue._connect() as conn:
            with conn.transaction():
                history = conn.execute(
                    sql.SQL("""insert into {} ("user", product_code, product_description,
                               format, quantity, status, kind, image_id, image_name)
                               values (%s, '', %s, 'custom_label_3_columns', %s, 'queued',
                                       'custom_label', %s, %s) returning id""").format(sql.Identifier(self.settings.history_table)),
                    (user, image.name, quantity, image.id, image.name),
                ).fetchone()
                job_id = self.queue.enqueue(
                    kind="custom_label", documents=documents, requested_labels=quantity,
                    history_id=history["id"], connection=conn,
                )
        return PrintResponse(ok=True, job_id=job_id, history_id=history["id"], message="Trabajo agregado a la cola de impresion")
