from collections import defaultdict
from decimal import Decimal, InvalidOperation

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

from app.printer import BatchLabel, Printer
from app.schemas import (
    InventoryBatchItemResult,
    InventoryBatchPrintRequest,
    InventoryBatchPrintResponse,
    InventoryEntryBatchPrintRequest,
    InventoryEntryDocument,
    InventoryEntryItem,
    InventoryItem,
    InventoryPrintSettings,
    LabelFormat,
    PrintBatchHistory,
    Product,
)
from app.settings import Settings


INVENTORY_PRINT_LIMIT_KEY = "inventory_print_limit"
DEFAULT_MAX_LABELS_PER_BATCH = 400


class InventoryPrintError(RuntimeError):
    pass


class InventoryPrintService:
    def __init__(self, settings: Settings, printer: Printer) -> None:
        self.settings = settings
        self.printer = printer

    def _connect(self) -> psycopg.Connection:
        return psycopg.connect(
            host=self.settings.database_host,
            port=self.settings.database_port,
            dbname=self.settings.database_name,
            user=self.settings.database_user,
            password=self.settings.database_password,
            row_factory=dict_row,
        )

    def ensure_schema(self) -> None:
        if not self.settings.use_postgres:
            return

        with self._connect() as conn:
            conn.execute(
                """
                create table if not exists app_settings (
                    key text primary key,
                    value text not null,
                    updated_at timestamptz not null default now()
                )
                """
            )
            conn.execute(
                """
                create table if not exists print_batches (
                    id bigint generated by default as identity primary key,
                    timestamp timestamptz not null default now(),
                    "user" text not null,
                    format text not null,
                    warehouse text not null,
                    source text not null default 'inventory',
                    source_document text,
                    source_date date,
                    requested_labels integer not null check (requested_labels > 0),
                    printed_labels integer not null default 0 check (printed_labels >= 0),
                    failed_labels integer not null default 0 check (failed_labels >= 0),
                    status text not null check (status in ('success', 'partial', 'error')),
                    message text
                )
                """
            )
            conn.execute("alter table print_batches add column if not exists source text not null default 'inventory'")
            conn.execute("alter table print_batches add column if not exists source_document text")
            conn.execute("alter table print_batches add column if not exists source_date date")
            conn.execute(
                """
                create table if not exists print_batch_items (
                    id bigint generated by default as identity primary key,
                    batch_id bigint not null references print_batches(id) on delete cascade,
                    product_id bigint,
                    reference text not null,
                    product_description text not null,
                    barcode text not null,
                    presentation text not null,
                    inventory_quantity numeric(14, 4) not null,
                    requested_labels integer not null check (requested_labels > 0),
                    printed_labels integer not null default 0 check (printed_labels >= 0),
                    failed_labels integer not null default 0 check (failed_labels >= 0),
                    status text not null check (status in ('success', 'partial', 'error')),
                    message text
                )
                """
            )
            conn.execute(
                """
                insert into app_settings (key, value)
                values (%s, %s)
                on conflict (key) do nothing
                """,
                (INVENTORY_PRINT_LIMIT_KEY, str(DEFAULT_MAX_LABELS_PER_BATCH)),
            )
            conn.execute(
                "create index if not exists print_batches_timestamp_idx on print_batches (timestamp desc)"
            )
            conn.execute(
                "create index if not exists print_batch_items_batch_id_idx on print_batch_items (batch_id)"
            )

    def get_warehouses(self) -> list[str]:
        self._require_postgres()
        table = sql.Identifier(self.settings.inventory_table)
        with self._connect() as conn:
            rows = conn.execute(
                sql.SQL(
                    "select distinct bodega from {} where bodega <> '' order by bodega"
                ).format(table)
            ).fetchall()
        return [str(row["bodega"]) for row in rows]

    def search_inventory(
        self,
        *,
        warehouse: str,
        search: str | None,
        lines: list[str],
        availability: str,
        limit: int,
        offset: int,
    ) -> tuple[list[InventoryItem], int]:
        self._require_postgres()
        inventory_table = sql.Identifier(self.settings.inventory_table)
        products_table = sql.Identifier(self.settings.products_table)
        pattern = f"%{(search or '').strip()}%"
        selected_lines = [line for line in lines if line]

        query = sql.SQL(
            """
            select inv.id_inventory as id,
                   inv.bodega as warehouse,
                   inv.referencia as reference,
                   inv.inventario as inventory_quantity,
                   min(p.linea) filter (where p.id is not null) as sort_line,
                   min(p.descripcion) filter (where p.id is not null) as sort_description,
                   coalesce(
                       jsonb_agg(
                           jsonb_build_object(
                               'id', p.id,
                               'line', p.linea,
                               'product_code', p.referencia,
                               'description', p.descripcion,
                               'unit_of_measure', p.um_siesa,
                               'barcode', p.codigo_barra,
                               'barcode_unit_measure', p.unidad_de_medida_barras,
                               'quantity_per_unit', p.cantidadxum,
                               'own_code', p.codigo_propio,
                               'presentation_quantity', concat_ws(
                                   ' ',
                                   nullif(p.cantidadxum, ''),
                                   nullif(p.unidad_de_medida_barras, '')
                               )
                           )
                           order by p.codigo_propio desc, p.cantidadxum, p.codigo_barra
                       ) filter (where p.id is not null),
                       '[]'::jsonb
                   ) as presentations
            from {inventory} as inv
            left join {products} as p
              on p.referencia = inv.referencia
             and p.codigo_propio = true
             and (
                 %(line_count)s = 0
                 or p.linea = any(%(lines)s::text[])
             )
            where inv.bodega = %(warehouse)s
              and (
                  %(line_count)s = 0
                  or exists (
                      select 1
                      from {products} as line_product
                      where line_product.referencia = inv.referencia
                        and line_product.codigo_propio = true
                        and line_product.linea = any(%(lines)s::text[])
                  )
              )
              and (
                  %(search)s = ''
                  or inv.referencia ilike %(pattern)s
                  or exists (
                      select 1
                      from {products} as searched_product
                      where searched_product.referencia = inv.referencia
                        and searched_product.codigo_propio = true
                        and (
                            searched_product.descripcion ilike %(pattern)s
                            or searched_product.codigo_barra ilike %(pattern)s
                            or searched_product.linea ilike %(pattern)s
                        )
                  )
              )
            group by inv.id_inventory, inv.bodega, inv.referencia, inv.inventario
            order by sort_line nulls last, sort_description nulls last, inv.referencia
            """
        ).format(inventory=inventory_table, products=products_table)

        with self._connect() as conn:
            rows = conn.execute(
                query,
                {
                    "warehouse": warehouse,
                    "search": (search or "").strip(),
                    "pattern": pattern,
                    "lines": selected_lines,
                    "line_count": len(selected_lines),
                },
            ).fetchall()

        items = [self._inventory_item_from_row(row) for row in rows]
        if availability == "printable":
            items = [item for item in items if item.printable]
        elif availability == "unprintable":
            items = [item for item in items if not item.printable]

        total = len(items)
        return items[offset : offset + limit], total

    def get_settings(self) -> InventoryPrintSettings:
        self._require_postgres()
        with self._connect() as conn:
            row = conn.execute(
                "select value from app_settings where key = %s",
                (INVENTORY_PRINT_LIMIT_KEY,),
            ).fetchone()
        value = int(row["value"]) if row else DEFAULT_MAX_LABELS_PER_BATCH
        return InventoryPrintSettings(max_labels_per_batch=value)

    def get_inventory_selection(
        self,
        *,
        warehouse: str,
        references: list[str],
    ) -> list[InventoryItem]:
        unique_references = set(references)
        items, _ = self.search_inventory(
            warehouse=warehouse,
            search=None,
            lines=[],
            availability="all",
            limit=100_000,
            offset=0,
        )
        return [item for item in items if item.reference in unique_references]

    def search_entry_documents(
        self,
        *,
        warehouse: str,
        search: str | None,
        limit: int,
        offset: int,
    ) -> tuple[list[InventoryEntryDocument], int]:
        self._require_postgres()
        entries_table = sql.Identifier(self.settings.inventory_entries_table)
        pattern = f"%{(search or '').strip()}%"
        query = sql.SQL(
            """
            select max(nullif(proveedor_razon_social, '')) as provider_name,
                   documento as document,
                   bodega as warehouse,
                   max(fecha) as date,
                   count(distinct referencia) as reference_count,
                   coalesce(sum(entradas_inv), 0) as total_entry_quantity
            from {entries}
            where bodega = %(warehouse)s
              and (
                  %(search)s = ''
                  or documento ilike %(pattern)s
                  or referencia ilike %(pattern)s
                  or proveedor_razon_social ilike %(pattern)s
              )
            group by documento, bodega
            order by max(fecha) desc, documento desc
            """
        ).format(entries=entries_table)

        with self._connect() as conn:
            rows = conn.execute(
                query,
                {
                    "warehouse": warehouse,
                    "search": (search or "").strip(),
                    "pattern": pattern,
                },
            ).fetchall()

        total = len(rows)
        documents = [InventoryEntryDocument.model_validate(row) for row in rows]
        return documents[offset : offset + limit], total

    def get_entry_document_items(
        self,
        *,
        warehouse: str,
        document: str,
    ) -> list[InventoryEntryItem]:
        self._require_postgres()
        entries_table = sql.Identifier(self.settings.inventory_entries_table)
        products_table = sql.Identifier(self.settings.products_table)
        query = sql.SQL(
            """
            select entry.id_inventory_entries as id,
                   entry.bodega as warehouse,
                   entry.documento as document,
                   entry.fecha as date,
                   entry.referencia as reference,
                   entry.entradas_inv as entry_quantity,
                   min(p.linea) filter (where p.id is not null) as sort_line,
                   min(p.descripcion) filter (where p.id is not null) as sort_description,
                   coalesce(
                       jsonb_agg(
                           jsonb_build_object(
                               'id', p.id,
                               'line', p.linea,
                               'product_code', p.referencia,
                               'description', p.descripcion,
                               'unit_of_measure', p.um_siesa,
                               'barcode', p.codigo_barra,
                               'barcode_unit_measure', p.unidad_de_medida_barras,
                               'quantity_per_unit', p.cantidadxum,
                               'own_code', p.codigo_propio,
                               'presentation_quantity', concat_ws(
                                   ' ',
                                   nullif(p.cantidadxum, ''),
                                   nullif(p.unidad_de_medida_barras, '')
                               )
                           )
                           order by p.cantidadxum, p.codigo_barra
                       ) filter (where p.id is not null),
                       '[]'::jsonb
                   ) as presentations
            from {entries} as entry
            left join {products} as p
              on p.referencia = entry.referencia
             and p.codigo_propio = true
            where entry.bodega = %(warehouse)s
              and entry.documento = %(document)s
            group by entry.id_inventory_entries, entry.bodega, entry.documento,
                     entry.fecha, entry.referencia, entry.entradas_inv
            order by sort_line nulls last, sort_description nulls last, entry.referencia
            """
        ).format(entries=entries_table, products=products_table)

        with self._connect() as conn:
            rows = conn.execute(
                query,
                {
                    "warehouse": warehouse,
                    "document": document,
                },
            ).fetchall()
        return [self._entry_item_from_row(row) for row in rows]

    def update_settings(self, payload: InventoryPrintSettings) -> InventoryPrintSettings:
        self._require_postgres()
        with self._connect() as conn:
            conn.execute(
                """
                insert into app_settings (key, value, updated_at)
                values (%s, %s, now())
                on conflict (key) do update
                set value = excluded.value,
                    updated_at = excluded.updated_at
                """,
                (INVENTORY_PRINT_LIMIT_KEY, str(payload.max_labels_per_batch)),
            )
        return payload

    def print_batch(
        self,
        payload: InventoryBatchPrintRequest,
        *,
        user: str,
    ) -> InventoryBatchPrintResponse:
        self._require_postgres()
        configured_limit = self.get_settings().max_labels_per_batch
        requested_labels = sum(item.quantity for item in payload.items)
        if requested_labels > configured_limit:
            raise InventoryPrintError(
                f"El lote solicita {requested_labels} etiquetas y el limite configurado es {configured_limit}."
            )

        inventory_table = sql.Identifier(self.settings.inventory_table)
        products_table = sql.Identifier(self.settings.products_table)
        formats_table = sql.Identifier(self.settings.formats_table)

        validated: list[tuple[InventoryBatchItemResult, Product]] = []
        seen_inventory_ids: set[int] = set()
        with self._connect() as conn:
            format_row = conn.execute(
                sql.SQL(
                    """
                    select id, name, code, width_mm, height_mm, preview_type, active, template_file
                    from {}
                    where code = %s and active = true
                    """
                ).format(formats_table),
                (payload.format,),
            ).fetchone()
            if format_row is None:
                raise InventoryPrintError("El formato seleccionado no existe o esta inactivo.")
            label_format = LabelFormat.model_validate(format_row)

            for item in payload.items:
                if item.quantity <= 0:
                    continue
                if item.inventory_id in seen_inventory_ids:
                    raise InventoryPrintError("Un articulo de inventario aparece repetido en el lote.")
                seen_inventory_ids.add(item.inventory_id)

                row = conn.execute(
                    sql.SQL(
                        """
                        select inv.id_inventory,
                               inv.bodega,
                               inv.referencia,
                               inv.inventario,
                               p.id,
                               p.linea as line,
                               p.referencia as product_code,
                               p.descripcion as description,
                               p.um_siesa as unit_of_measure,
                               p.codigo_barra as barcode,
                               p.unidad_de_medida_barras as barcode_unit_measure,
                               p.cantidadxum as quantity_per_unit,
                               p.codigo_propio as own_code,
                               concat_ws(
                                   ' ',
                                   nullif(p.cantidadxum, ''),
                                   nullif(p.unidad_de_medida_barras, '')
                               ) as presentation_quantity
                        from {inventory} as inv
                        inner join {products} as p
                          on p.id = %(product_id)s
                         and p.referencia = inv.referencia
                         and p.codigo_propio = true
                        where inv.id_inventory = %(inventory_id)s
                        """
                    ).format(inventory=inventory_table, products=products_table),
                    {
                        "inventory_id": item.inventory_id,
                        "product_id": item.product_id,
                    },
                ).fetchone()
                if row is None:
                    raise InventoryPrintError(
                        f"El articulo {item.inventory_id} o su presentacion ya no estan disponibles."
                    )
                if row["bodega"] != payload.warehouse:
                    raise InventoryPrintError(
                        f"El articulo {row['referencia']} no pertenece a la bodega seleccionada."
                    )

                product = Product.model_validate(row)
                self._validate_presentation(product)
                validated.append(
                    (
                        InventoryBatchItemResult(
                            product_id=product.id,
                            reference=str(row["referencia"]),
                            description=product.description,
                            barcode=product.barcode,
                            presentation=product.presentation_quantity,
                            inventory_quantity=row["inventario"],
                            requested_labels=item.quantity,
                            printed_labels=0,
                            failed_labels=0,
                            status="error",
                        ),
                        product,
                    )
                )

        labels = [
            BatchLabel(item_key=index, product=product)
            for index, (result, product) in enumerate(validated)
            for _ in range(result.requested_labels)
        ]
        if not labels:
            raise InventoryPrintError("El lote no tiene etiquetas para imprimir.")
        requested_labels = len(labels)
        outcomes = self.printer.print_batch(label_format=label_format, labels=labels)

        results: list[InventoryBatchItemResult] = []
        for index, (result, _) in enumerate(validated):
            outcome = outcomes[index]
            if outcome.failed_labels == 0:
                status = "success"
            elif outcome.printed_labels == 0:
                status = "error"
            else:
                status = "partial"
            results.append(
                result.model_copy(
                    update={
                        "printed_labels": outcome.printed_labels,
                        "failed_labels": outcome.failed_labels,
                        "status": status,
                        "message": "; ".join(outcome.errors) or None,
                    }
                )
            )

        printed_labels = sum(item.printed_labels for item in results)
        failed_labels = sum(item.failed_labels for item in results)
        if failed_labels == 0:
            batch_status = "success"
            message = None
        elif printed_labels == 0:
            batch_status = "error"
            message = "No se pudo imprimir ninguna etiqueta del lote."
        else:
            batch_status = "partial"
            message = (
                f"Se imprimieron {printed_labels} etiquetas y {failed_labels} presentaron error."
            )

        batch_id = self._save_batch_history(
            user=user,
            format_code=label_format.code,
            warehouse=payload.warehouse,
            requested_labels=requested_labels,
            printed_labels=printed_labels,
            failed_labels=failed_labels,
            status=batch_status,
            message=message,
            items=results,
        )
        return InventoryBatchPrintResponse(
            batch_id=batch_id,
            status=batch_status,
            requested_labels=requested_labels,
            printed_labels=printed_labels,
            failed_labels=failed_labels,
            message=message,
            items=results,
        )

    def print_entry_batch(
        self,
        payload: InventoryEntryBatchPrintRequest,
        *,
        user: str,
    ) -> InventoryBatchPrintResponse:
        self._require_postgres()
        configured_limit = self.get_settings().max_labels_per_batch
        requested_labels = sum(item.quantity for item in payload.items)
        if requested_labels > configured_limit:
            raise InventoryPrintError(
                f"El lote solicita {requested_labels} etiquetas y el limite configurado es {configured_limit}."
            )

        entries_table = sql.Identifier(self.settings.inventory_entries_table)
        products_table = sql.Identifier(self.settings.products_table)
        formats_table = sql.Identifier(self.settings.formats_table)

        validated: list[tuple[InventoryBatchItemResult, Product]] = []
        seen_entry_ids: set[int] = set()
        source_date = None
        with self._connect() as conn:
            format_row = conn.execute(
                sql.SQL(
                    """
                    select id, name, code, width_mm, height_mm, preview_type, active, template_file
                    from {}
                    where code = %s and active = true
                    """
                ).format(formats_table),
                (payload.format,),
            ).fetchone()
            if format_row is None:
                raise InventoryPrintError("El formato seleccionado no existe o esta inactivo.")
            label_format = LabelFormat.model_validate(format_row)

            for item in payload.items:
                if item.quantity <= 0:
                    continue
                if item.entry_id in seen_entry_ids:
                    raise InventoryPrintError("Una entrada aparece repetida en el lote.")
                seen_entry_ids.add(item.entry_id)

                row = conn.execute(
                    sql.SQL(
                        """
                        select entry.id_inventory_entries,
                               entry.bodega,
                               entry.documento,
                               entry.fecha,
                               entry.referencia,
                               entry.entradas_inv,
                               p.id,
                               p.linea as line,
                               p.referencia as product_code,
                               p.descripcion as description,
                               p.um_siesa as unit_of_measure,
                               p.codigo_barra as barcode,
                               p.unidad_de_medida_barras as barcode_unit_measure,
                               p.cantidadxum as quantity_per_unit,
                               p.codigo_propio as own_code,
                               concat_ws(
                                   ' ',
                                   nullif(p.cantidadxum, ''),
                                   nullif(p.unidad_de_medida_barras, '')
                               ) as presentation_quantity
                        from {entries} as entry
                        inner join {products} as p
                          on p.id = %(product_id)s
                         and p.referencia = entry.referencia
                         and p.codigo_propio = true
                        where entry.id_inventory_entries = %(entry_id)s
                          and entry.bodega = %(warehouse)s
                          and entry.documento = %(document)s
                        """
                    ).format(entries=entries_table, products=products_table),
                    {
                        "entry_id": item.entry_id,
                        "product_id": item.product_id,
                        "warehouse": payload.warehouse,
                        "document": payload.document,
                    },
                ).fetchone()
                if row is None:
                    raise InventoryPrintError(
                        f"La entrada {item.entry_id} o su presentacion ya no estan disponibles."
                    )

                if source_date is None:
                    source_date = row["fecha"]
                elif source_date != row["fecha"]:
                    raise InventoryPrintError("El documento contiene entradas con fechas distintas.")

                product = Product.model_validate(row)
                self._validate_presentation(product)
                validated.append(
                    (
                        InventoryBatchItemResult(
                            product_id=product.id,
                            reference=str(row["referencia"]),
                            description=product.description,
                            barcode=product.barcode,
                            presentation=product.presentation_quantity,
                            inventory_quantity=row["entradas_inv"],
                            requested_labels=item.quantity,
                            printed_labels=0,
                            failed_labels=0,
                            status="error",
                        ),
                        product,
                    )
                )

        labels = [
            BatchLabel(item_key=index, product=product)
            for index, (result, product) in enumerate(validated)
            for _ in range(result.requested_labels)
        ]
        if not labels:
            raise InventoryPrintError("El lote no tiene etiquetas para imprimir.")
        requested_labels = len(labels)
        outcomes = self.printer.print_batch(label_format=label_format, labels=labels)

        results: list[InventoryBatchItemResult] = []
        for index, (result, _) in enumerate(validated):
            outcome = outcomes[index]
            if outcome.failed_labels == 0:
                status = "success"
            elif outcome.printed_labels == 0:
                status = "error"
            else:
                status = "partial"
            results.append(
                result.model_copy(
                    update={
                        "printed_labels": outcome.printed_labels,
                        "failed_labels": outcome.failed_labels,
                        "status": status,
                        "message": "; ".join(outcome.errors) or None,
                    }
                )
            )

        printed_labels = sum(item.printed_labels for item in results)
        failed_labels = sum(item.failed_labels for item in results)
        if failed_labels == 0:
            batch_status = "success"
            message = None
        elif printed_labels == 0:
            batch_status = "error"
            message = "No se pudo imprimir ninguna etiqueta del lote."
        else:
            batch_status = "partial"
            message = (
                f"Se imprimieron {printed_labels} etiquetas y {failed_labels} presentaron error."
            )

        batch_id = self._save_batch_history(
            user=user,
            format_code=label_format.code,
            warehouse=payload.warehouse,
            requested_labels=requested_labels,
            printed_labels=printed_labels,
            failed_labels=failed_labels,
            status=batch_status,
            message=message,
            items=results,
            source="inventory_entry",
            source_document=payload.document,
            source_date=source_date,
        )
        return InventoryBatchPrintResponse(
            batch_id=batch_id,
            status=batch_status,
            requested_labels=requested_labels,
            printed_labels=printed_labels,
            failed_labels=failed_labels,
            message=message,
            items=results,
        )

    def get_batch_history(self) -> list[PrintBatchHistory]:
        self._require_postgres()
        with self._connect() as conn:
            batches = conn.execute(
                """
                select id, timestamp, "user", format, warehouse, requested_labels,
                       printed_labels, failed_labels, status, message,
                       source, source_document, source_date
                from print_batches
                order by timestamp desc
                limit 200
                """
            ).fetchall()
            if not batches:
                return []

            batch_ids = [row["id"] for row in batches]
            item_rows = conn.execute(
                """
                select batch_id, product_id, reference, product_description, barcode,
                       presentation, inventory_quantity, requested_labels,
                       printed_labels, failed_labels, status, message
                from print_batch_items
                where batch_id = any(%s)
                order by id
                """,
                (batch_ids,),
            ).fetchall()

        grouped: dict[int, list[InventoryBatchItemResult]] = defaultdict(list)
        for row in item_rows:
            grouped[int(row["batch_id"])].append(
                InventoryBatchItemResult(
                    product_id=row["product_id"],
                    reference=row["reference"],
                    description=row["product_description"],
                    barcode=row["barcode"],
                    presentation=row["presentation"],
                    inventory_quantity=row["inventory_quantity"],
                    requested_labels=row["requested_labels"],
                    printed_labels=row["printed_labels"],
                    failed_labels=row["failed_labels"],
                    status=row["status"],
                    message=row["message"],
                )
            )
        return [
            PrintBatchHistory(
                **row,
                items=grouped[int(row["id"])],
            )
            for row in batches
        ]

    def _inventory_item_from_row(self, row: dict) -> InventoryItem:
        presentations: list[Product] = []
        for item in row["presentations"]:
            try:
                product = Product.model_validate(item)
                self._validate_presentation(product)
            except (ValueError, InventoryPrintError):
                continue
            presentations.append(product)

        inventory_quantity = Decimal(row["inventory_quantity"])
        if inventory_quantity <= 0:
            reason = "La existencia no es positiva."
        elif not presentations:
            reason = "No tiene una presentacion valida en productos."
        else:
            reason = None

        return InventoryItem(
            id=row["id"],
            warehouse=row["warehouse"],
            reference=row["reference"],
            inventory_quantity=inventory_quantity,
            presentations=presentations,
            printable=reason is None,
            unavailable_reason=reason,
        )

    def _entry_item_from_row(self, row: dict) -> InventoryEntryItem:
        presentations: list[Product] = []
        for item in row["presentations"]:
            try:
                product = Product.model_validate(item)
                self._validate_presentation(product)
            except (ValueError, InventoryPrintError):
                continue
            presentations.append(product)

        entry_quantity = Decimal(row["entry_quantity"])
        if entry_quantity <= 0:
            reason = "La entrada no es positiva."
        elif not presentations:
            reason = "No tiene una presentacion valida en productos."
        else:
            reason = None

        return InventoryEntryItem(
            id=row["id"],
            warehouse=row["warehouse"],
            document=row["document"],
            date=row["date"],
            reference=row["reference"],
            entry_quantity=entry_quantity,
            presentations=presentations,
            printable=reason is None,
            unavailable_reason=reason,
        )

    @staticmethod
    def _validate_presentation(product: Product) -> None:
        try:
            quantity = Decimal(product.quantity_per_unit or "")
        except InvalidOperation as exc:
            raise InventoryPrintError("La cantidad por UM no es valida.") from exc
        if quantity <= 0:
            raise InventoryPrintError("La cantidad por UM debe ser positiva.")
        if not product.barcode.strip():
            raise InventoryPrintError("La presentacion no tiene codigo de barras.")

    def _save_batch_history(
        self,
        *,
        user: str,
        format_code: str,
        warehouse: str,
        source: str = "inventory",
        source_document: str | None = None,
        source_date=None,
        requested_labels: int,
        printed_labels: int,
        failed_labels: int,
        status: str,
        message: str | None,
        items: list[InventoryBatchItemResult],
    ) -> int:
        with self._connect() as conn:
            with conn.transaction():
                batch = conn.execute(
                    """
                    insert into print_batches
                        ("user", format, warehouse, source, source_document, source_date,
                         requested_labels, printed_labels, failed_labels, status, message)
                    values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    returning id
                    """,
                    (
                        user,
                        format_code,
                        warehouse,
                        source,
                        source_document,
                        source_date,
                        requested_labels,
                        printed_labels,
                        failed_labels,
                        status,
                        message,
                    ),
                ).fetchone()
                batch_id = int(batch["id"])
                with conn.cursor() as cursor:
                    cursor.executemany(
                        """
                        insert into print_batch_items
                            (batch_id, product_id, reference, product_description, barcode,
                             presentation, inventory_quantity, requested_labels,
                             printed_labels, failed_labels, status, message)
                        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        [
                            (
                                batch_id,
                                item.product_id,
                                item.reference,
                                item.description,
                                item.barcode,
                                item.presentation,
                                item.inventory_quantity,
                                item.requested_labels,
                                item.printed_labels,
                                item.failed_labels,
                                item.status,
                                item.message,
                            )
                            for item in items
                        ],
                    )
        return batch_id

    def _require_postgres(self) -> None:
        if not self.settings.use_postgres:
            raise InventoryPrintError(
                "La impresion desde inventario requiere CLINIC_DATA_SOURCE=postgres."
            )
