from __future__ import annotations

import json
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row

from app.printer import QueuedZplDocument
from app.schemas import (
    AgentHeartbeatRequest,
    AgentJobResultRequest,
    AgentPrintDocument,
    AgentPrintJob,
    PrinterAgentStatus,
)
from app.settings import Settings


class PrintQueueError(RuntimeError):
    pass


class PrintQueueService:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    def _connect(self) -> psycopg.Connection:
        return psycopg.connect(
            host=self.settings.database_host,
            port=self.settings.database_port,
            dbname=self.settings.database_name,
            user=self.settings.database_user,
            password=self.settings.database_password,
            row_factory=dict_row,
        )

    def ensure_schema(self) -> None:
        if not self.settings.use_postgres:
            return
        statuses = "'queued', 'processing', 'success', 'partial', 'error', 'unknown'"
        with self._connect() as conn:
            conn.execute("alter table print_history drop constraint if exists print_history_status_check")
            conn.execute(f"alter table print_history add constraint print_history_status_check check (status in ({statuses}))")
            conn.execute("alter table print_batches drop constraint if exists print_batches_status_check")
            conn.execute(f"alter table print_batches add constraint print_batches_status_check check (status in ({statuses}))")
            conn.execute("alter table print_batch_items drop constraint if exists print_batch_items_status_check")
            conn.execute(f"alter table print_batch_items add constraint print_batch_items_status_check check (status in ({statuses}))")
            conn.execute(
                """
                create table if not exists print_agents (
                    agent_id text primary key,
                    printer_name text not null,
                    printer_ok boolean not null default false,
                    message text,
                    last_seen_at timestamptz not null
                )
                """
            )
            conn.execute(
                f"""
                create table if not exists print_jobs (
                    id bigint generated by default as identity primary key,
                    kind text not null,
                    history_id bigint,
                    batch_id bigint,
                    printer_name text not null,
                    status text not null check (status in ({statuses})),
                    requested_labels integer not null default 0,
                    printed_labels integer not null default 0,
                    failed_labels integer not null default 0,
                    agent_id text,
                    created_at timestamptz not null default now(),
                    claimed_at timestamptz,
                    completed_at timestamptz,
                    message text
                )
                """
            )
            conn.execute(
                f"""
                create table if not exists print_job_documents (
                    id bigint generated by default as identity primary key,
                    job_id bigint not null references print_jobs(id) on delete cascade,
                    sequence integer not null,
                    zpl text not null,
                    item_counts jsonb not null default '{{}}'::jsonb,
                    status text not null check (status in ({statuses})),
                    message text,
                    unique (job_id, sequence)
                )
                """
            )
            conn.execute("create index if not exists print_jobs_status_idx on print_jobs (status, id)")

    def enqueue(
        self,
        *,
        kind: str,
        documents: list[QueuedZplDocument],
        requested_labels: int,
        history_id: int | None = None,
        batch_id: int | None = None,
    ) -> int:
        if not documents:
            raise PrintQueueError("El trabajo no contiene documentos para imprimir.")
        with self._connect() as conn:
            with conn.transaction():
                job = conn.execute(
                    """
                    insert into print_jobs
                        (kind, history_id, batch_id, printer_name, status, requested_labels)
                    values (%s, %s, %s, %s, 'queued', %s)
                    returning id
                    """,
                    (kind, history_id, batch_id, self.settings.printer_name, requested_labels),
                ).fetchone()
                job_id = int(job["id"])
                with conn.cursor() as cursor:
                    cursor.executemany(
                        """
                        insert into print_job_documents
                            (job_id, sequence, zpl, item_counts, status)
                        values (%s, %s, %s, %s::jsonb, 'queued')
                        """,
                        [
                            (
                                job_id,
                                sequence,
                                document.zpl,
                                json.dumps(document.item_counts),
                            )
                            for sequence, document in enumerate(documents, start=1)
                        ],
                    )
        return job_id

    def heartbeat(self, payload: AgentHeartbeatRequest) -> PrinterAgentStatus:
        self._validate_agent_id(payload.agent_id)
        with self._connect() as conn:
            row = conn.execute(
                """
                insert into print_agents
                    (agent_id, printer_name, printer_ok, message, last_seen_at)
                values (%s, %s, %s, %s, now())
                on conflict (agent_id) do update set
                    printer_name = excluded.printer_name,
                    printer_ok = excluded.printer_ok,
                    message = excluded.message,
                    last_seen_at = excluded.last_seen_at
                returning agent_id, printer_name, printer_ok, message, last_seen_at
                """,
                (payload.agent_id, payload.printer_name, payload.printer_ok, payload.message),
            ).fetchone()
        return self._agent_status(row)

    def get_agent_status(self) -> PrinterAgentStatus:
        with self._connect() as conn:
            row = conn.execute(
                """
                select agent_id, printer_name, printer_ok, message, last_seen_at
                from print_agents where agent_id = %s
                """,
                (self.settings.print_agent_id,),
            ).fetchone()
        if row is None:
            return PrinterAgentStatus(
                agent_id=self.settings.print_agent_id,
                printer_name=self.settings.printer_name,
                online=False,
                printer_ok=False,
                message="El agente aun no se ha conectado.",
            )
        return self._agent_status(row)

    def claim(self, agent_id: str) -> AgentPrintJob | None:
        self._validate_agent_id(agent_id)
        self.mark_stale_jobs()
        with self._connect() as conn:
            with conn.transaction():
                job = conn.execute(
                    """
                    with candidate as (
                        select id from print_jobs
                        where status = 'queued'
                        order by id
                        for update skip locked
                        limit 1
                    )
                    update print_jobs as job
                    set status = 'processing', agent_id = %s, claimed_at = now(), message = null
                    from candidate
                    where job.id = candidate.id
                    returning job.id, job.kind, job.printer_name, job.history_id, job.batch_id
                    """,
                    (agent_id,),
                ).fetchone()
                if job is None:
                    return None
                conn.execute(
                    "update print_job_documents set status = 'processing' where job_id = %s",
                    (job["id"],),
                )
                self._set_related_status(conn, job, "processing", None)
                rows = conn.execute(
                    """
                    select id, sequence, zpl from print_job_documents
                    where job_id = %s order by sequence
                    """,
                    (job["id"],),
                ).fetchall()
        return AgentPrintJob(
            id=job["id"],
            kind=job["kind"],
            printer_name=job["printer_name"],
            documents=[AgentPrintDocument.model_validate(row) for row in rows],
        )

    def complete(self, job_id: int, payload: AgentJobResultRequest) -> dict[str, object]:
        self._validate_agent_id(payload.agent_id)
        results = {result.document_id: result for result in payload.documents}
        with self._connect() as conn:
            with conn.transaction():
                job = conn.execute(
                    "select * from print_jobs where id = %s for update",
                    (job_id,),
                ).fetchone()
                if job is None:
                    raise PrintQueueError("Trabajo de impresion no encontrado.")
                if job["status"] != "processing" or job["agent_id"] != payload.agent_id:
                    raise PrintQueueError("El trabajo no esta reclamado por este agente.")
                documents = conn.execute(
                    "select id, item_counts from print_job_documents where job_id = %s order by sequence",
                    (job_id,),
                ).fetchall()
                expected = {int(document["id"]) for document in documents}
                if set(results) != expected:
                    raise PrintQueueError("El resultado no incluye todos los documentos del trabajo.")

                item_totals: dict[int, list[int]] = {}
                messages: list[str] = []
                for document in documents:
                    result = results[int(document["id"])]
                    status = "success" if result.ok else "error"
                    conn.execute(
                        "update print_job_documents set status = %s, message = %s where id = %s",
                        (status, result.message, document["id"]),
                    )
                    if result.message and not result.ok:
                        messages.append(result.message)
                    for raw_key, count in dict(document["item_counts"]).items():
                        printed, failed = item_totals.setdefault(int(raw_key), [0, 0])
                        if result.ok:
                            printed += int(count)
                        else:
                            failed += int(count)
                        item_totals[int(raw_key)] = [printed, failed]

                printed_labels = sum(value[0] for value in item_totals.values())
                failed_labels = sum(value[1] for value in item_totals.values())
                if failed_labels == 0:
                    status = "success"
                elif printed_labels == 0:
                    status = "error"
                else:
                    status = "partial"
                message = "; ".join(dict.fromkeys(messages)) or None
                conn.execute(
                    """
                    update print_jobs set status = %s, printed_labels = %s, failed_labels = %s,
                        completed_at = now(), message = %s
                    where id = %s
                    """,
                    (status, printed_labels, failed_labels, message, job_id),
                )
                self._finalize_related(conn, job, status, message, item_totals)
        return {"job_id": job_id, "status": status}

    def mark_stale_jobs(self) -> None:
        with self._connect() as conn:
            with conn.transaction():
                rows = conn.execute(
                    """
                    update print_jobs
                    set status = 'unknown', completed_at = now(),
                        message = 'El agente no confirmo el resultado; verifique la cola antes de reimprimir.'
                    where status = 'processing'
                      and claimed_at < now() - (%s * interval '1 second')
                    returning id, history_id, batch_id, message
                    """,
                    (self.settings.print_agent_stale_seconds,),
                ).fetchall()
                for row in rows:
                    conn.execute(
                        "update print_job_documents set status = 'unknown', message = %s where job_id = %s and status = 'processing'",
                        (row["message"], row["id"]),
                    )
                    self._set_related_status(conn, row, "unknown", row["message"])

    def retry(self, job_id: int) -> int:
        with self._connect() as conn:
            with conn.transaction():
                job = conn.execute(
                    "select * from print_jobs where id = %s for update",
                    (job_id,),
                ).fetchone()
                if job is None or job["status"] not in {"error", "unknown"}:
                    raise PrintQueueError("Solo se pueden reintentar trabajos con error o resultado incierto.")
                new_job = conn.execute(
                    """
                    insert into print_jobs
                        (kind, history_id, batch_id, printer_name, status, requested_labels)
                    values (%s, %s, %s, %s, 'queued', %s)
                    returning id
                    """,
                    (
                        job["kind"],
                        job["history_id"],
                        job["batch_id"],
                        job["printer_name"],
                        job["requested_labels"],
                    ),
                ).fetchone()
                new_job_id = int(new_job["id"])
                conn.execute(
                    """
                    insert into print_job_documents (job_id, sequence, zpl, item_counts, status)
                    select %s, sequence, zpl, item_counts, 'queued'
                    from print_job_documents where job_id = %s order by sequence
                    """,
                    (new_job_id, job_id),
                )
                self._set_related_status(conn, job, "queued", None, reset=True)
        return new_job_id

    def _validate_agent_id(self, agent_id: str) -> None:
        if agent_id != self.settings.print_agent_id:
            raise PrintQueueError("Agente de impresion no autorizado.")

    def _agent_status(self, row: dict) -> PrinterAgentStatus:
        age = (datetime.now(timezone.utc) - row["last_seen_at"]).total_seconds()
        return PrinterAgentStatus(
            agent_id=row["agent_id"],
            printer_name=row["printer_name"],
            online=age <= self.settings.print_agent_stale_seconds,
            printer_ok=row["printer_ok"],
            last_seen_at=row["last_seen_at"],
            message=row["message"],
        )

    @staticmethod
    def _set_related_status(conn, job: dict, status: str, message: str | None, reset: bool = False) -> None:
        if job.get("history_id") is not None:
            conn.execute(
                "update print_history set status = %s, message = %s where id = %s",
                (status, message, job["history_id"]),
            )
        if job.get("batch_id") is not None:
            counts = ", printed_labels = 0, failed_labels = 0" if reset else ""
            conn.execute(
                f"update print_batches set status = %s, message = %s {counts} where id = %s",
                (status, message, job["batch_id"]),
            )
            conn.execute(
                f"update print_batch_items set status = %s, message = %s {counts} where batch_id = %s",
                (status, message, job["batch_id"]),
            )

    @staticmethod
    def _finalize_related(conn, job: dict, status: str, message: str | None, item_totals: dict[int, list[int]]) -> None:
        if job.get("history_id") is not None:
            conn.execute(
                "update print_history set status = %s, message = %s where id = %s",
                (status, message, job["history_id"]),
            )
        if job.get("batch_id") is None:
            return
        rows = conn.execute(
            "select id from print_batch_items where batch_id = %s order by id",
            (job["batch_id"],),
        ).fetchall()
        for index, row in enumerate(rows):
            printed, failed = item_totals.get(index, [0, 0])
            item_status = "success" if failed == 0 else "error" if printed == 0 else "partial"
            conn.execute(
                """
                update print_batch_items
                set printed_labels = %s, failed_labels = %s, status = %s, message = %s
                where id = %s
                """,
                (printed, failed, item_status, message if failed else None, row["id"]),
            )
        conn.execute(
            """
            update print_batches set printed_labels = %s, failed_labels = %s,
                status = %s, message = %s where id = %s
            """,
            (
                sum(value[0] for value in item_totals.values()),
                sum(value[1] for value in item_totals.values()),
                status,
                message,
                job["batch_id"],
            ),
        )
