drop table if exists products;

create table products (
  id bigint generated by default as identity primary key,
  referencia text not null,
  descripcion text not null,
  um_siesa text not null,
  codigo_barra text not null,
  cantidadxum text not null,
  unidad_de_medida_barras text not null,
  linea text not null,
  codigo_propio boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists inventory_entries (
  id_inventory_entries bigint generated by default as identity primary key,
  referencia text not null,
  entradas_inv numeric(14, 4) not null default 0,
  documento text not null,
  fecha date not null,
  bodega text not null,
  proveedor_nit text not null default '',
  proveedor_razon_social text not null default '',
  created_at timestamptz not null default now()
);

alter table inventory_entries add column if not exists proveedor_nit text not null default '';
alter table inventory_entries add column if not exists proveedor_razon_social text not null default '';

create table if not exists inventory (
  id_inventory bigint generated by default as identity primary key,
  referencia text not null,
  inventario numeric(14, 4) not null default 0,
  bodega text not null,
  created_at timestamptz not null default now()
);

comment on table inventory_entries is
  'Entradas incrementales con retencion maxima de dos meses calendario.';

alter table products drop constraint if exists products_referencia_key;
alter table products drop constraint if exists products_codigo_barra_key;

create table if not exists label_formats (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  width_mm integer not null,
  height_mm integer not null,
  preview_type text not null check (preview_type in ('format1', 'format2')),
  active boolean not null default true,
  template_file text not null default '',
  created_at timestamptz not null default now()
);

alter table label_formats add column if not exists template_file text not null default '';

create table if not exists print_history (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  "user" text not null,
  product_code text not null,
  product_description text not null,
  format text not null,
  quantity integer not null check (quantity > 0),
  status text not null check (status in ('success', 'error')),
  message text
);

create table if not exists app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists print_batches (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  "user" text not null,
  format text not null,
  warehouse text not null,
  source text not null default 'inventory',
  source_document text,
  source_date date,
  requested_labels integer not null check (requested_labels > 0),
  printed_labels integer not null default 0 check (printed_labels >= 0),
  failed_labels integer not null default 0 check (failed_labels >= 0),
  status text not null check (status in ('success', 'partial', 'error')),
  message text
);

create table if not exists print_batch_items (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references print_batches(id) on delete cascade,
  product_id bigint,
  reference text not null,
  product_description text not null,
  barcode text not null,
  presentation text not null,
  inventory_quantity numeric(14, 4) not null,
  requested_labels integer not null check (requested_labels > 0),
  printed_labels integer not null default 0 check (printed_labels >= 0),
  failed_labels integer not null default 0 check (failed_labels >= 0),
  status text not null check (status in ('success', 'partial', 'error')),
  message text
);

drop index if exists products_product_code_idx;
create index if not exists products_referencia_idx on products (referencia);
drop index if exists products_barcode_idx;
drop index if exists products_codigo_barra_uidx;
create index if not exists products_codigo_barra_idx on products (codigo_barra);
create index if not exists products_linea_idx on products (linea);
create index if not exists inventory_entries_referencia_idx on inventory_entries (referencia);
create index if not exists inventory_entries_fecha_idx on inventory_entries (fecha desc);
create index if not exists inventory_entries_documento_idx on inventory_entries (documento);
create index if not exists inventory_entries_bodega_idx on inventory_entries (bodega);
create unique index if not exists inventory_entries_source_uidx
  on inventory_entries (referencia, documento, fecha, bodega);
create index if not exists inventory_referencia_idx on inventory (referencia);
create index if not exists inventory_bodega_idx on inventory (bodega);
create unique index if not exists label_formats_template_file_uidx
  on label_formats (template_file)
  where template_file <> '';
create index if not exists print_history_timestamp_idx on print_history (timestamp desc);
create index if not exists print_batches_timestamp_idx on print_batches (timestamp desc);
create index if not exists print_batch_items_batch_id_idx on print_batch_items (batch_id);
